asio:
  opensuse: [asio-devel]
avahi-daemon:
  opensuse: [avahi]
avrdude:
  opensuse: [avrdude]
benchmark:
  opensuse: [benchmark-devel]
binutils:
  opensuse: [binutils-devel]
bison:
  opensuse: [bison]
boost:
  opensuse: [libboost_atomic1_66_0-devel, libboost_headers1_66_0-devel, libboost_system1_66_0-devel, libboost_thread1_66_0-devel, libboost_chrono1_66_0-devel, libboost_date_time1_66_0-devel, libboost_serialization1_66_0-devel, libboost_filesystem1_66_0-devel, libboost_program_options1_66_0-devel, libboost_python-py2_7-1_66_0-devel, libboost_python-py3-1_66_0-devel, libboost_signals1_66_0-devel, libboost_regex1_66_0-devel, libboost_iostreams1_66_0-devel]
clang:
  opensuse: [clang]
clang-format:
  opensuse: [clang]
clang-tidy:
  opensuse: [clang-tools]
cppcheck:
  opensuse: [cppcheck]
dpkg:
  opensuse: [dpkg]
emacs:
  opensuse: [emacs]
festival:
  opensuse: [festival]
fmt:
  opensuse: [fmt-devel]
gawk:
  opensuse: [gawk]
gfortran:
  opensuse: [gcc11-fortran]
gnuplot:
  opensuse: [gnuplot]
gstreamer1.0-alsa:
  opensuse: [gstreamer-plugins-base]
java:
  opensuse: [java-1_8_0-openjdk]
jq:
  opensuse: [jq]
libavahi-core-dev:
  opensuse: [libavahi-devel]
libblas-dev:
  opensuse: [blas-devel]
libceres-dev:
  opensuse: [libceres-devel]
libcunit-dev:
  opensuse: [cunit-devel]
libfftw3:
  opensuse: [fftw3, fftw3-devel]
libgeos++-dev:
  opensuse: [geos-devel]
libgphoto-dev:
  opensuse: [libgphoto2-devel]
libgsl:
  opensuse: [gsl-devel]
libhdf5-dev:
  opensuse: [hdf5-devel]
libmicrohttpd:
  opensuse: [libmicrohttpd-devel]
libncurses-dev:
  opensuse: [ncurses-devel]
libnlopt-dev:
  opensuse: [nlopt-devel]
libogre:
  opensuse: [libOgreMain-devel, libOgreOverlay-devel, libOgrePaging-devel, libOgreProperty-devel, libOgreRTShaderSystem-devel, libOgreTerrain-devel, libOgreVolume-devel]
libomp-dev:
  opensuse: [libomp11-devel]
libopenblas-dev:
  opensuse: [openblas-devel]
libopenexr-dev:
  opensuse: [openexr-devel]
libpcap:
  opensuse: [libpcap-devel]
libpulse-dev:
  opensuse: [libpulse-devel]
libqt5-websockets-dev:
  opensuse: [libqt5-qtwebsockets-devel]
libqt5-xml:
  opensuse: [libQt5Xml5]
libqt5x11extras5-dev:
  opensuse: [libqt5-qtx11extras-devel]
libqwt-qt5-dev:
  opensuse: [libQt5Widgets-devel]
libraw1394-dev:
  opensuse: [libraw1394-devel]
libreadline-dev:
  opensuse: [readline-devel]
libspnav-dev:
  opensuse: [libspnav-devel, libX11-devel]
libsqlite3-dev:
  opensuse: [sqlite3-devel]
libxmlrpc-c++:
  opensuse: [xmlrpc-c-devel]
libxmu-dev:
  opensuse: [libXmu-devel]
linux-kernel-headers:
  opensuse: [kernel-devel]
lm-sensors:
  opensuse: [sensors]
log4cplus:
  opensuse: [log4cplus-devel]
lua5.2-dev:
  opensuse: [lua53-devel]
msgpack:
  opensuse: [msgpack-devel]
nkf:
  opensuse: [nkf]
npm:
  opensuse: [npm-default]
opencl-headers:
  opensuse: [opencl-headers]
postgresql:
  opensuse: [postgresql-server, postgresql-contrib]
procps:
  opensuse: [procps]
pugixml-dev:
  opensuse: [pugixml-devel]
python-dev:
  opensuse: [python-devel]
qtmultimedia5-dev:
  opensuse: [libqt5-qtmultimedia-devel]
spdlog:
  opensuse: [spdlog-devel]
sshpass:
  opensuse: [sshpass]
swig:
  opensuse: [swig]
sysstat:
  opensuse: [sysstat]
udev:
  opensuse: [systemd]
usbutils:
  opensuse: [usbutils]
util-linux:
  opensuse: [util-linux]
v4l-utils:
  opensuse: [v4l-utils]
vlc:
  opensuse: [vlc]
wx-common:
  opensuse: [wxGTK3-3_2-devel]
xfonts-75dpi:
  opensuse: [xorg-x11-fonts-legacy]
xterm:
  opensuse: [xterm]
xvfb:
  opensuse: [xorg-x11-server]
zbar:
  opensuse: [zbar, libzbar-devel]
