acl:
  opensuse:
    '15.3': [acl, libacl-devel]
asio:
  opensuse:
    '15.3': [asio-devel]
avahi-daemon:
  opensuse:
    '15.3': [avahi]
avrdude:
  opensuse:
    '15.3': [avrdude]
benchmark:
  opensuse:
    '15.3': [benchmark-devel]
binutils:
  opensuse:
    '15.3': [binutils-devel]
bison:
  opensuse:
    '15.3': [bison]
boost:
  opensuse:
    '15.3': [libboost_atomic1_66_0-devel, libboost_headers1_66_0-devel, libboost_system1_66_0-devel, libboost_thread1_66_0-devel, libboost_chrono1_66_0-devel, libboost_date_time1_66_0-devel, libboost_serialization1_66_0-devel, libboost_filesystem1_66_0-devel, libboost_program_options1_66_0-devel, libboost_python-py2_7-1_66_0-devel, libboost_python-py3-1_66_0-devel, libboost_signals1_66_0-devel, libboost_regex1_66_0-devel, libboost_iostreams1_66_0-devel]
clang:
  opensuse:
    '15.3': [clang]
clang-format:
  opensuse:
    '15.3': [clang]
clang-tidy:
  opensuse:
    '15.3': [clang-tools]
cppcheck:
  opensuse:
    '15.3': [cppcheck]
dpkg:
  opensuse:
    '15.3': [dpkg]
emacs:
  opensuse:
    '15.3': [emacs]
festival:
  opensuse:
    '15.3': [festival]
file:
  opensuse:
    '15.3': [file]
fmt:
  opensuse:
    '15.3': [fmt-devel]
gawk:
  opensuse:
    '15.3': [gawk]
gfortran:
  opensuse:
    '15.3': [gcc11-fortran]
gnuplot:
  opensuse:
    '15.3': [gnuplot]
gstreamer1.0-alsa:
  opensuse:
    '15.3': [gstreamer-plugins-base]
java:
  opensuse:
    '15.3': [java-1_8_0-openjdk]
jq:
  opensuse:
    '15.3': [jq]
libatomic:
  opensuse:
    '15.3': [libatomic1]
libavahi-core-dev:
  opensuse:
    '15.3': [libavahi-devel]
libblas-dev:
  opensuse:
    '15.3': [blas-devel]
libceres-dev:
  opensuse:
    '15.3': [libceres-devel]
libcunit-dev:
  opensuse:
    '15.3': [cunit-devel]
libfftw3:
  opensuse:
    '15.3': [fftw3, fftw3-devel]
libfreetype6:
  opensuse:
    '15.3': [libfreetype6]
libfreetype6-dev:
  opensuse:
    '15.3': [freetype2-devel]
libgeos++-dev:
  opensuse:
    '15.3': [geos-devel]
libgphoto-dev:
  opensuse:
    '15.3': [libgphoto2-devel]
libgsl:
  opensuse:
    '15.3': [gsl-devel]
libhdf5-dev:
  opensuse:
    '15.3': [hdf5-devel]
libmicrohttpd:
  opensuse:
    '15.3': [libmicrohttpd-devel]
libncurses-dev:
  opensuse:
    '15.3': [ncurses-devel]
libnlopt-dev:
  opensuse:
    '15.3': [nlopt-devel]
libogre:
  opensuse:
    '15.3': [libOgreMain-devel, libOgreOverlay-devel, libOgrePaging-devel, libOgreProperty-devel, libOgreRTShaderSystem-devel, libOgreTerrain-devel, libOgreVolume-devel]
libomp-dev:
  opensuse:
    '15.3': [libomp11-devel]
libopenblas-dev:
  opensuse:
    '15.3': [openblas-devel]
libopenexr-dev:
  opensuse:
    '15.3': [openexr-devel]
libpcap:
  opensuse:
    '15.3': [libpcap-devel]
libpulse-dev:
  opensuse:
    '15.3': [libpulse-devel]
libqt5-websockets-dev:
  opensuse:
    '15.3': [libqt5-qtwebsockets-devel]
libqt5-xml:
  opensuse:
    '15.3': [libQt5Xml5]
libqt5x11extras5-dev:
  opensuse:
    '15.3': [libqt5-qtx11extras-devel]
libqwt-qt5-dev:
  opensuse:
    '15.3': [libQt5Widgets-devel]
libraw1394-dev:
  opensuse:
    '15.3': [libraw1394-devel]
libreadline-dev:
  opensuse:
    '15.3': [readline-devel]
libspnav-dev:
  opensuse:
    '15.3': [libspnav-devel, libX11-devel]
libsqlite3-dev:
  opensuse:
    '15.3': [sqlite3-devel]
libxmlrpc-c++:
  opensuse:
    '15.3': [xmlrpc-c-devel]
libxml2-utils:
  opensuse:
    '15.3': [libxml2-tools]
libxmu-dev:
  opensuse:
    '15.3': [libXmu-devel]
libxrandr:
  opensuse:
    '15.3': [libXrandr-devel]
libzstd-dev:
  opensuse:
    '15.3': [libzstd-devel]
linux-kernel-headers:
  opensuse:
    '15.3': [kernel-devel]
lm-sensors:
  opensuse:
    '15.3': [sensors]
log4cplus:
  opensuse:
    '15.3': [log4cplus-devel]
lua5.2-dev:
  opensuse:
    '15.3': [lua53-devel]
msgpack:
  opensuse:
    '15.3': [msgpack-devel]
nkf:
  opensuse:
    '15.3': [nkf]
npm:
  opensuse:
    '15.3': [npm-default]
opencl-headers:
  opensuse:
    '15.3': [opencl-headers]
postgresql:
  opensuse:
    '15.3': [postgresql-server, postgresql-contrib]
procps:
  opensuse:
    '15.3': [procps]
pugixml-dev:
  opensuse:
    '15.3': [pugixml-devel]
pybind11-dev:
  opensuse:
    '15.3': [python3-pybind11-devel]
python-dev:
  opensuse:
    '15.3': [python-devel]
qtmultimedia5-dev:
  opensuse:
    '15.3': [libqt5-qtmultimedia-devel]
sdl2:
  opensuse:
    '15.3': [libSDL2-devel]
sdl2-image:
  opensuse:
    '15.3': [libSDL2_image-devel]
sdl2-mixer:
  opensuse:
    '15.3': [libSDL2_mixer-devel]
sdl2-ttf:
  opensuse:
    '15.3': [libSDL2_ttf-devel]
spdlog:
  opensuse:
    '15.3': [spdlog-devel]
sshpass:
  opensuse:
    '15.3': [sshpass]
swig:
  opensuse:
    '15.3': [swig]
sysstat:
  opensuse:
    '15.3': [sysstat]
udev:
  opensuse:
    '15.3': [systemd]
uncrustify:
  opensuse:
    '15.3': [uncrustify]
usbutils:
  opensuse:
    '15.3': [usbutils]
util-linux:
  opensuse:
    '15.3': [util-linux]
v4l-utils:
  opensuse:
    '15.3': [v4l-utils]
vlc:
  opensuse:
    '15.3': [vlc]
wx-common:
  opensuse:
    '15.3': [wxGTK3-3_2-devel]
xfonts-75dpi:
  opensuse:
    '15.3': [xorg-x11-fonts-legacy]
xterm:
  opensuse:
    '15.3': [xterm]
xvfb:
  opensuse:
    '15.3': [xorg-x11-server]
yaml:
  opensuse:
    '15.3': [libyaml-devel]
zbar:
  opensuse:
    '15.3': [zbar, libzbar-devel]
