cppcheck:
  opensuse: [cppcheck]
libatomic:
  opensuse: [libatomic1]
liblttng-ctl-dev:
  opensuse: [lttng-tools-devel]
liblttng-ust-dev:
  opensuse: [lttng-ust-devel]
libqt6gui6t64:
  opensuse: [libQt6Gui6]
libqt6widgets6t64:
  opensuse: [libQt6Widgets6]
pybind11-dev:
  opensuse: [python313-pybind11-devel]
yaml:
  opensuse: [libyaml-0-2]
