acl:
  opensuse: [acl, libacl-devel]
asio:
  opensuse: [asio-devel]
benchmark:
  opensuse: [benchmark-devel]
boost:
  opensuse: [libboost_atomic1_86_0-devel, libboost_headers1_86_0-devel, libboost_system1_86_0-devel, libboost_thread1_86_0-devel, libboost_chrono1_86_0-devel, libboost_date_time1_86_0-devel, libboost_serialization1_86_0-devel, libboost_filesystem1_86_0-devel, libboost_program_options1_86_0-devel, libboost_python-py3-1_86_0-devel, libboost_signals1_86_0-devel, libboost_regex1_86_0-devel, libboost_iostreams1_86_0-devel]
clang:
  opensuse: [clang]
cli11:
  opensuse: [cli11-devel]
cppcheck:
  opensuse: [cppcheck]
file:
  opensuse: [file]
fmt:
  opensuse: [fmt-devel]
libatomic:
  opensuse: [libatomic1]
libboost-atomic:
  opensuse: [libboost_atomic1_86_0]
libboost-atomic-dev:
  opensuse: [libboost_atomic1_86_0-devel]
libboost-chrono:
  opensuse: [libboost_chrono1_86_0]
libboost-chrono-dev:
  opensuse: [libboost_chrono1_86_0-devel]
libboost-coroutine:
  opensuse: [libboost_coroutine1_86_0]
libboost-coroutine-dev:
  opensuse: [libboost_coroutine1_86_0-devel]
libboost-date-time:
  opensuse: [libboost_date_time1_86_0]
libboost-date-time-dev:
  opensuse: [libboost_date_time1_86_0-devel]
libboost-dev:
  opensuse: [libboost_headers1_86_0-devel]
libboost-filesystem:
  opensuse: [libboost_filesystem1_86_0]
libboost-filesystem-dev:
  opensuse: [libboost_filesystem1_86_0-devel]
libboost-iostreams:
  opensuse: [libboost_iostreams1_86_0]
libboost-iostreams-dev:
  opensuse: [libboost_iostreams1_86_0-devel]
libboost-math:
  opensuse: [libboost_math1_86_0]
libboost-math-dev:
  opensuse: [libboost_math1_86_0-devel]
libboost-numpy-dev:
  opensuse: [libboost_numpy-py3-1_86_0-devel]
libboost-program-options:
  opensuse: [libboost_program_options1_86_0]
libboost-program-options-dev:
  opensuse: [libboost_program_options1_86_0-devel]
libboost-python:
  opensuse: [libboost_python-py3-1_86_0]
libboost-python-dev:
  opensuse: [libboost_python-py3-1_86_0-devel]
libboost-random:
  opensuse: [libboost_random1_86_0]
libboost-random-dev:
  opensuse: [libboost_random1_86_0-devel]
libboost-regex:
  opensuse: [libboost_regex1_86_0]
libboost-regex-dev:
  opensuse: [libboost_regex1_86_0-devel]
libboost-serialization:
  opensuse: [libboost_serialization1_86_0]
libboost-serialization-dev:
  opensuse: [libboost_serialization1_86_0-devel]
libboost-system:
  opensuse: [libboost_system1_86_0]
libboost-system-dev:
  opensuse: [libboost_system1_86_0-devel]
libboost-thread:
  opensuse: [libboost_thread1_86_0]
libboost-thread-dev:
  opensuse: [libboost_thread1_86_0-devel]
libboost-timer:
  opensuse: [libboost_timer1_86_0]
libboost-timer-dev:
  opensuse: [libboost_timer1_86_0-devel]
libfreetype-dev:
  opensuse: [freetype2-devel]
libfreetype6:
  opensuse: [libfreetype6]
liblttng-ctl-dev:
  opensuse: [lttng-tools-devel]
liblttng-ust-dev:
  opensuse: [lttng-ust-devel]
liblz4:
  opensuse: [liblz4-1]
libncurses-dev:
  opensuse: [ncurses-devel]
libopencv-core:
  opensuse: [libopencv410]
libopencv-highgui:
  opensuse: [libopencv_highgui410]
libopencv-imgcodecs:
  opensuse: [libopencv_imgcodecs410]
libopencv-imgproc:
  opensuse: [libopencv_ximgproc410]
libopencv-videoio:
  opensuse: [libopencv_videoio410]
libqt5-qml:
  opensuse: [libQtQuick5]
libqt5-svg:
  opensuse: [libQt5Svg5]
libqt6gui6t64:
  opensuse: [libQt6Gui6]
libqt6opengl6t64:
  opensuse: [libQt6OpenGL6]
libqt6svg6:
  opensuse: [libQt6Svg6]
libqt6widgets6t64:
  opensuse: [libQt6Widgets6]
libsqlite3-dev:
  opensuse: [sqlite3-devel]
libxaw:
  opensuse: [libXaw-devel]
libxi-dev:
  opensuse: [libXi-devel]
libxml2-utils:
  opensuse: [libxml2-tools]
libxrandr:
  opensuse: [libXrandr-devel]
libxxf86vm:
  opensuse: [libXxf86vm-devel]
libzip-dev:
  opensuse: [libzip-devel]
libzstd-dev:
  opensuse: [libzstd-devel]
lttng-tools:
  opensuse: [lttng-tools]
nlohmann-json-dev:
  opensuse: [nlohmann_json-devel]
procps:
  opensuse: [procps]
pybind11-dev:
  opensuse: [python313-pybind11-devel]
qt6-base-dev:
  opensuse: [qt6-base-devel]
qt6-svg-dev:
  opensuse: [qt6-svg-devel]
spdlog:
  opensuse: [spdlog-devel]
uncrustify:
  opensuse: [uncrustify]
xvfb:
  opensuse: [xorg-x11-server-Xvfb]
yaml:
  opensuse: [libyaml-0-2]
