cppcheck:
  opensuse: [cppcheck]
libatomic:
  opensuse: [libatomic1]
liblttng-ctl-dev:
  opensuse: [lttng-tools-devel]
liblttng-ust-dev:
  opensuse: [lttng-ust-devel]
libncurses-dev:
  opensuse: [ncurses-devel]
libqt6gui6t64:
  opensuse: [libQt6Gui6]
libqt6widgets6t64:
  opensuse: [libQt6Widgets6]
libsqlite3-dev:
  opensuse: [sqlite3-devel]
libxrandr:
  opensuse: [libXrandr-devel]
procps:
  opensuse: [procps]
pybind11-dev:
  opensuse: [python313-pybind11-devel]
uncrustify:
  opensuse: [uncrustify]
yaml:
  opensuse: [libyaml-0-2]
