asio:
  opensuse: [asio-devel]
benchmark:
  opensuse: [benchmark-devel]
clang:
  opensuse: [clang]
cli11:
  opensuse: [cli11-devel]
cppcheck:
  opensuse: [cppcheck]
libatomic:
  opensuse: [libatomic1]
libfreetype6:
  opensuse: [libfreetype6]
liblttng-ctl-dev:
  opensuse: [lttng-tools-devel]
liblttng-ust-dev:
  opensuse: [lttng-ust-devel]
libncurses-dev:
  opensuse: [ncurses-devel]
libqt6gui6t64:
  opensuse: [libQt6Gui6]
libqt6svg6:
  opensuse: [libQt6Svg6]
libqt6widgets6t64:
  opensuse: [libQt6Widgets6]
libsqlite3-dev:
  opensuse: [sqlite3-devel]
libxml2-utils:
  opensuse: [libxml2-tools]
libxrandr:
  opensuse: [libXrandr-devel]
libzstd-dev:
  opensuse: [libzstd-devel]
nlohmann-json-dev:
  opensuse: [nlohmann_json-devel]
procps:
  opensuse: [procps]
pybind11-dev:
  opensuse: [python313-pybind11-devel]
spdlog:
  opensuse: [spdlog-devel]
uncrustify:
  opensuse: [uncrustify]
yaml:
  opensuse: [libyaml-0-2]
